# Generated by Django 5.1.1 on 2025-05-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='starting_balance',
            field=models.FloatField(blank=True, max_length=8, null=True),
        ),
    ]
