# Generated by Django 5.1.1 on 2025-05-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_starting_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
