# Generated by Django 5.1.1 on 2025-05-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_starting_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='starting_balance',
            field=models.FloatField(blank=True, max_length=6, null=True),
        ),
    ]
